### ISSUE TITLE
Missing val, test ids in splits.json

### ISSUE THREAD

**Issue by nilsleh** [vishalned/MMEarth-data#1]
Hi @vishalned , I noticed that the splits.json files for each of the dataset variants do not contain any indices for the val and test splits but are just empty lists. Is that information available somewhere else, since in your paper you report results for a specific test set? Thanks in advance!

**Comment by vishalned** [comment]
Hey, we do not use val and test splits. In our paper MMEarth is used for pretraining and hence the splits is not needed. This was just created incase someone else wants to use the splits for some other reason. (you can always recreate the splits, using the utils/script.py and change the split percentages in the function.
